--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/NoteLand/PlotSquaredPM
projects:
  PlotSquaredPM:
    icon: "icon.png"
    path: ""
    libs:
      - src: dktapps-pm-pl/pmforms/pmforms
        version: ^2.1.0
...